using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class cameraFollw : MonoBehaviour
{
    private Vector3 offset = new Vector3(0f, 0f, -10f);//define the offset from camera to the player
    private float smoothTime = 0.25f;//defines the approximate time it will take camera to reach the target
    private Vector3 velocity = Vector3.zero;//for velocity


    [SerializeField] private Transform target;
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        Vector3 targetPosition = target.position + offset;//add offset to the position of target
        transform.position = Vector3.SmoothDamp(transform.position, targetPosition, ref velocity, smoothTime);
    }
}
